export const HTML_ATTRIBUTES_MAP = {
    "accept": "accept",
    "accept-charset": "acceptCharset",
    "accesskey": "accessKey",
    "action": "action",
    "align": "align",
    "allow": "allow",
    "alpha": "alpha",
    "alt": "alt",
    "as": "as",
    "async": "async",
    "autocapitalize": "autoCapitalize",
    "autocomplete": "autoComplete",
    "autoplay": "autoplay",
    "background": "background",
    "bgcolor": "bgColor",
    "border": "border",
    "capture": "capture",
    "charset": "charset",
    "checked": "checked",
    "cite": "cite",
    "class": "class",
    "color": "color",
    "colorspace": "colorSpace",
    "cols": "cols",
    "colspan": "colSpan",
    "content": "content",
    "contenteditable": "contentEditable",
    "controls": "controls",
    "coords": "coords",
    "crossorigin": "crossOrigin",
    "csp": "csp",
    "data": "data",
    "data-*": "data*",
    "datetime": "datetime",
    "decoding": "decoding",
    "default": "default",
    "defer": "defer",
    "dir": "dir",
    "dirname": "dirName",
    "disabled": "disabled",
    "download": "download",
    "draggable": "draggable",
    "enctype": "enctype",
    "enterkeyhint": "enterKeyHint",
    "elementtiming": "elementTiming",
    "for": "htmlFor",
    "form": "form",
    "formaction": "formAction",
    "formenctype": "formEncType",
    "formmethod": "formMethod",
    "formnovalidate": "formNoValidate",
    "formtarget": "formTarget",
    "headers": "headers",
    "height": "height",
    "hidden": "hidden",
    "high": "high",
    "href": "href",
    "hreflang": "hrefLang",
    "http-equiv": "httpEquiv",
    "id": "id",
    "integrity": "integrity",
    "inputmode": "inputMode",
    "ismap": "isMap",
    "itemprop": "itemProp",
    "kind": "kind",
    "label": "label",
    "lang": "lang",
    "language": "language",
    "loading": "loading",
    "list": "list",
    "loop": "loop",
    "low": "low",
    "max": "max",
    "maxlength": "maxLength",
    "minlength": "minLength",
    "media": "media",
    "method": "method",
    "min": "min",
    "multiple": "multiple",
    "muted": "muted",
    "name": "name",
    "novalidate": "noValidate",
    "open": "open",
    "optimum": "optimum",
    "pattern": "pattern",
    "ping": "ping",
    "placeholder": "placeholder",
    "playsinline": "playsInline",
    "poster": "poster",
    "preload": "preload",
    "readonly": "readOnly",
    "referrerpolicy": "referrerPolicy",
    "rel": "rel",
    "required": "required",
    "reversed": "reversed",
    "role": "role",
    "rows": "rows",
    "rowspan": "rowSpan",
    "sandbox": "sandbox",
    "scope": "scope",
    "selected": "selected",
    "shape": "shape",
    "size": "size",
    "sizes": "sizes",
    "slot": "slot",
    "span": "span",
    "spellcheck": "spellCheck",
    "src": "src",
    "srcdoc": "srcDoc",
    "srclang": "srcLang",
    "srcset": "srcSet",
    "start": "start",
    "step": "step",
    "style": "style",
    "summary": "summary",
    "tabindex": "tabIndex",
    "target": "target",
    "title": "title",
    "translate": "translate",
    "type": "type",
    "usemap": "useMap",
    "value": "value",
    "width": "width",
    "wrap": "wrap"
} as const


export const HTML_BOOLEAN_ATTRIBUTES_SET = new Set([
    "async",
    "autoplay",
    "checked",
    "contentEditable",
    "controls",
    "default",
    "defer",
    "disabled",
    "download",
    "draggable",
    "hidden",
    "isMap",
    "itemScope",
    "loop",
    "multiple",
    "muted",
    "noValidate",
    "open",
    "playsInline",
    "readOnly",
    "required",
    "reversed",
    "selected",
    "spellCheck",
    "translate",
    "wrap"
])

export const HTML_NODE_NAMES_SET = new Set([
    "html",
    "base",
    "head",
    "link",
    "meta",
    "style",
    "title",
    "body",
    "address",
    "article",
    "aside",
    "footer",
    "header",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hgroup",
    "main",
    "nav",
    "section",
    "search",
    "blockquote",
    "dd",
    "div",
    "dl",
    "dt",
    "figcaption",
    "figure",
    "hr",
    "li",
    "menu",
    "ol",
    "p",
    "pre",
    "ul",
    "a",
    "abbr",
    "b",
    "bdi",
    "bdo",
    "br",
    "cite",
    "code",
    "data",
    "dfn",
    "em",
    "i",
    "kbd",
    "mark",
    "q",
    "rp",
    "rt",
    "ruby",
    "s",
    "samp",
    "small",
    "span",
    "strong",
    "sub",
    "sup",
    "time",
    "u",
    "var",
    "wbr",
    "area",
    "audio",
    "img",
    "map",
    "track",
    "video",
    "embed",
    "fencedframe",
    "iframe",
    "object",
    "picture",
    "source",
    "svg",
    "math",
    "canvas",
    "noscript",
    "script",
    "del",
    "ins",
    "caption",
    "col",
    "colgroup",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "tr",
    "button",
    "datalist",
    "fieldset",
    "form",
    "input",
    "label",
    "legend",
    "meter",
    "optgroup",
    "option",
    "output",
    "progress",
    "select",
    "selectedcontent",
    "textarea",
    "details",
    "dialog",
    "summary",
    "slot",
    "template"
])
